# Generated by Django 4.1.2 on 2022-10-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beboo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brainwork',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='brainwork',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='brainwork',
            name='address',
        ),
        migrations.RemoveField(
            model_name='brainwork',
            name='password',
        ),
        migrations.AddField(
            model_name='brainwork',
            name='Descriptions',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='brainwork',
            name='Title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
