# Generated by Django 4.1.2 on 2022-10-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beboo', '0002_remove_brainwork_email_remove_brainwork_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brainwork',
            name='Descriptions',
            field=models.TextField(null=True),
        ),
    ]
